import { ITopDomains } from "@/types/top-domains";

export const WEEK_TOP_CONTENT_DOMAINS: ITopDomains[] = [
  {
    domain: "anydesk.com",
    categories: [6, 19],
    total_requests: 2155886,
  },
  {
    domain: "nviidia.com",
    categories: [24],
    total_requests: 1313744,
  },
  {
    domain: "nvidia.cm",
    categories: [24],
    total_requests: 582771,
  },
  { domain: "weibo.cn", categories: [2], total_requests: 233570 },
  {
    domain: "activestate.com",
    categories: [6, 19],
    total_requests: 102112,
  },
  {
    domain: "andbeyond.media",
    categories: [6],
    total_requests: 98408,
  },
  {
    domain: "ezchip.com",
    categories: [6, 19],
    total_requests: 55264,
  },
  {
    domain: "reasonsecurity.com",
    categories: [6, 19],
    total_requests: 51764,
  },
  {
    domain: "screenconnect.com",
    categories: [6, 19],
    total_requests: 42311,
  },
  {
    domain: "surfshark.com",
    categories: [6, 19, 25],
    total_requests: 42241,
  },
  {
    domain: "erate.co.il",
    categories: [6],
    total_requests: 34340,
  },
  {
    domain: "acidcow.com",
    categories: [2],
    total_requests: 31817,
  },
  { domain: "mtl.com", categories: [6], total_requests: 28978 },
  {
    domain: "vk.com",
    categories: [2, 39, 52],
    total_requests: 27738,
  },
  {
    domain: "hola.org",
    categories: [6, 19, 25],
    total_requests: 25789,
  },
  {
    domain: "fanpop.com",
    categories: [2],
    total_requests: 22642,
  },
  { domain: "7086.in", categories: [39], total_requests: 16669 },
  {
    domain: "digitaloceanspaces.com",
    categories: [6, 19],
    total_requests: 16318,
  },
  {
    domain: "polyfill.io",
    categories: [19, 66],
    total_requests: 15067,
  },
  {
    domain: "torrent.eu.org",
    categories: [39, 52],
    total_requests: 14713,
  },
  {
    domain: "tamersunion.org",
    categories: [39],
    total_requests: 14220,
  },
  {
    domain: "demonii.com",
    categories: [39],
    total_requests: 12691,
  },
  {
    domain: "theoks.net",
    categories: [39],
    total_requests: 12604,
  },
  { domain: "dler.org", categories: [39], total_requests: 12033 },
  {
    domain: "therarbg.com",
    categories: [39],
    total_requests: 10194,
  },
  {
    domain: "nvidiaa.com",
    categories: [6, 19],
    total_requests: 10139,
  },
  {
    domain: "explodie.org",
    categories: [39],
    total_requests: 9872,
  },
  {
    domain: "moack.co.kr",
    categories: [39],
    total_requests: 8824,
  },
  {
    domain: "desync.com",
    categories: [39],
    total_requests: 8651,
  },
  { domain: "vuze.com", categories: [39], total_requests: 8616 },
  { domain: "mnaspm.com", categories: [2], total_requests: 8450 },
  {
    domain: "privateinternetaccess.com",
    categories: [19, 25],
    total_requests: 7085,
  },
  { domain: "9gag.com", categories: [2], total_requests: 6298 },
  {
    domain: "privateinternetaccess.com",
    categories: [6, 19, 25],
    total_requests: 6128,
  },
  { domain: "rarbg.to", categories: [39], total_requests: 5853 },
  { domain: "bt4g.com", categories: [39], total_requests: 5715 },
  {
    domain: "linodeobjects.com",
    categories: [6, 19],
    total_requests: 5194,
  },
  {
    domain: "anirena.com",
    categories: [39],
    total_requests: 4975,
  },
  {
    domain: "utorrent.com",
    categories: [39],
    total_requests: 4848,
  },
  { domain: "rarbg.me", categories: [39], total_requests: 4788 },
  {
    domain: "endscan.com",
    categories: [39],
    total_requests: 4026,
  },
  {
    domain: "celebsfirst.com",
    categories: [2],
    total_requests: 3965,
  },
  {
    domain: "opentor.org",
    categories: [39],
    total_requests: 3801,
  },
  {
    domain: "internetwarriors.net",
    categories: [39],
    total_requests: 3533,
  },
  {
    domain: "discountmags.com",
    categories: [2],
    total_requests: 3203,
  },
  {
    domain: "leechers-paradise.org",
    categories: [39],
    total_requests: 3174,
  },
  {
    domain: "trackerfix.com",
    categories: [39],
    total_requests: 2963,
  },
  {
    domain: "leathercelebrities.com",
    categories: [2],
    total_requests: 2932,
  },
  { domain: "tfile.co", categories: [39], total_requests: 2447 },
  {
    domain: "darmowy-torrent.pl",
    categories: [39],
    total_requests: 2444,
  },
  {
    domain: "h-cdn.com",
    categories: [40, 71, 75],
    total_requests: 2248,
  },
  {
    domain: "aliexpress-media.com",
    categories: [39, 52],
    total_requests: 2235,
  },
  {
    domain: "coppersurfer.tk",
    categories: [39],
    total_requests: 2168,
  },
  {
    domain: "mancrushes.com",
    categories: [2],
    total_requests: 2104,
  },
  { domain: "51.la", categories: [39, 66], total_requests: 2057 },
  {
    domain: "cyberghostvpn.com",
    categories: [19, 25],
    total_requests: 2047,
  },
  {
    domain: "birdseye.photo",
    categories: [2],
    total_requests: 2003,
  },
  {
    domain: "publictracker.xyz",
    categories: [39],
    total_requests: 1897,
  },
  {
    domain: "123movies.link",
    categories: [39, 52],
    total_requests: 1843,
  },
  {
    domain: "vailresorts.com",
    categories: [6, 11],
    total_requests: 1775,
  },
  {
    domain: "pirateparty.gr",
    categories: [39],
    total_requests: 1751,
  },
  {
    domain: "bittorrent.com",
    categories: [39],
    total_requests: 1611,
  },
  {
    domain: "torrent.eu.org",
    categories: [39],
    total_requests: 1602,
  },
  { domain: "1zoom.me", categories: [2], total_requests: 1594 },
  {
    domain: "suntiros.com",
    categories: [2],
    total_requests: 1548,
  },
  { domain: "youpic.com", categories: [2], total_requests: 1459 },
  {
    domain: "redgifs.com",
    categories: [2],
    total_requests: 1360,
  },
  {
    domain: "clearbit.com",
    categories: [6, 19],
    total_requests: 1261,
  },
  {
    domain: "createsend1.com",
    categories: [11],
    total_requests: 1186,
  },
  { domain: "vador.com", categories: [2], total_requests: 1134 },
  { domain: "dim.com", categories: [2], total_requests: 1121 },
  { domain: "bing.net", categories: [2], total_requests: 1103 },
  { domain: "pixpa.com", categories: [6], total_requests: 1066 },
  {
    domain: "dearlady.us",
    categories: [2],
    total_requests: 1045,
  },
  {
    domain: "xhamster2.com",
    categories: [2],
    total_requests: 1034,
  },
  {
    domain: "chinesemov.com",
    categories: [39],
    total_requests: 1015,
  },
  {
    domain: "thehiveworks.com",
    categories: [2],
    total_requests: 1004,
  },
  { domain: "cyberia.is", categories: [39], total_requests: 996 },
  { domain: "bbrdbr.com", categories: [2], total_requests: 928 },
  {
    domain: "arenabg.com",
    categories: [39],
    total_requests: 818,
  },
  {
    domain: "pow7.com",
    categories: [39, 66],
    total_requests: 777,
  },
  {
    domain: "createsend1.com",
    categories: [6, 19],
    total_requests: 775,
  },
  { domain: "seedr.cc", categories: [39], total_requests: 730 },
  {
    domain: "onelaunch.com",
    categories: [39, 52, 66],
    total_requests: 727,
  },
  {
    domain: "malltop1.com",
    categories: [2],
    total_requests: 674,
  },
  { domain: "r2.dev", categories: [19], total_requests: 669 },
  {
    domain: "motherlesslive.com",
    categories: [2],
    total_requests: 656,
  },
  {
    domain: "theplace2.ru",
    categories: [2],
    total_requests: 653,
  },
  {
    domain: "inmotionhosting.com",
    categories: [6, 19],
    total_requests: 640,
  },
  {
    domain: "ballgloves.us.com",
    categories: [2],
    total_requests: 638,
  },
  { domain: "erome.com", categories: [2], total_requests: 613 },
  { domain: "imgsrc.ru", categories: [2], total_requests: 591 },
  { domain: "acgnx.se", categories: [39], total_requests: 590 },
  {
    domain: "mydownloadtube.net",
    categories: [39],
    total_requests: 576,
  },
  {
    domain: "wholesale-sex-toys.com",
    categories: [2],
    total_requests: 576,
  },
  {
    domain: "fmovies.cab",
    categories: [39],
    total_requests: 573,
  },
  { domain: "acg.rip", categories: [39], total_requests: 560 },
  {
    domain: "ural-region.net",
    categories: [2],
    total_requests: 530,
  },
  { domain: "xhcdn.com", categories: [2], total_requests: 528 },
  {
    domain: "myprogresspics.com",
    categories: [2],
    total_requests: 527,
  },
];
