export const CATEGORIES: string[] = [
  "Advertising",
  "Parked Sites & Domains",
  "Proxy & Filter Avoidance",
  "Translation Site",
  "Phishing & Deception",
  "Botnet",
  "Crypto Mining",
  "Malware",
  "New Domains",
  "Trackers",
  "Very New Domains",
  "Abortion",
  "Adult Content",
  "Alcohol & Tobacco",
  "Blogs & Personal Sites",
  "Business",
  "Webmail & Chat",
  "Dating & Personals",
  "Drugs",
  "Economy & Finance",
  "Education & Self Help",
  "Entertainment",
  "Food & Recipes",
  "Gambling",
  "Games",
  "Hacking & Cracking",
  "Health",
  "Humor",
  "Information Technology",
  "Jobs & Careers",
  "Media Sharing",
  "Message Boards & Forums",
  "News & Media",
  "Real Estate",
  "Religion",
  "Search Engines & Portals",
  "Shopping",
  "Social Networking",
  "Sports",
  "Streaming Media",
  "Travel",
  "Vehicles",
  "Virtual Reality",
  "Weapons",
  "P2P & Illegal",
  "Terrorism & Hate",
  "Government",
];
